name: Deploy to Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "spm.iotserver.uz"
          username: "muzaffarov"
          password: ${{ secrets.VM_PASSWORD }}
          source: "."
          target: "/home/muzaffarov/todoapp"

      - name: Connect and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "spm.iotserver.uz"
          username: "muzaffarov"
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /home/muzaffarov/todoapp
            
            # Create container based on the current state of main branch
            docker compose build
            
            # If existing container is running, stop and delete it
            docker compose down
            
            # Run the new container
            docker compose up -d
